<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>mtsuite.shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\core-filesystem\CoreFileSystem.csproj" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.0" />
  </ItemGroup>
</Project>